// Exports contract ABIs from Foundry artifacts into the app and keeper as typed `as const` TS modules.
// Usage: pnpm abi   (after `forge build` in /contracts)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const names = [
  ["SeriesFactory.sol", "SeriesFactory"],
  ["Note.sol", "Note"],
  ["Settlement.sol", "Settlement"],
  ["UnderwriterPool.sol", "UnderwriterPool"],
  ["SecondaryListings.sol", "SecondaryListings"],
  ["OracleAdapter.sol", "OracleAdapter"],
  ["MarketClock.sol", "MarketClock"],
  ["FeeCollector.sol", "FeeCollector"],
  ["ProjectTokenHooks.sol", "ProjectTokenHooks"],
  ["ComplianceRegistry.sol", "ComplianceRegistry"],
  ["YieldAdapter.sol", "YieldAdapter"],
  ["IAggregatorV3.sol", "IAggregatorV3"],
];
let src = "// AUTO-GENERATED by scripts/export-abis.mjs from contracts/out. Do not edit.\n\n";
for (const [file, name] of names) {
  const art = JSON.parse(readFileSync(join(out, file, `${name}.json`), "utf8"));
  src += `export const ${name}Abi = ${JSON.stringify(art.abi)} as const;\n\n`;
}
for (const target of [join(root, "app", "src", "abi"), join(root, "scripts", "src", "abi")]) {
  mkdirSync(target, { recursive: true });
  writeFileSync(join(target, "index.ts"), src);
  console.log("wrote", join(target, "index.ts"));
}
